# Generated by Django 4.2.7 on 2023-11-25 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_treatmentregion_patient_treatment_regions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.machinetype'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.machine'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.patient'),
        ),
    ]
